"""Structural estimation of the Rust MDP from observed choice panels.

Week-5 workhorse. Two estimators:

1. `estimate_nfxp` — full-solution maximum likelihood (Rust's nested fixed
   point): for each candidate (theta1, rc), solve the MDP by value iteration
   and evaluate the logit likelihood of the observed choices. Slow but
   consistent and simple; used to validate the whole pipeline.

2. `estimate_hotz_miller` — TODO (week 5): CCP-based estimator exploiting
   replacement as a renewal action (finite dependence). Steps: (i) estimate
   CCPs nonparametrically from the panel, (ii) use the Hotz-Miller inversion
   with the renewal property to express choice-value differences in terms of
   CCPs and flow utilities, (iii) estimate (theta1, rc) by pseudo-likelihood.

The point of the paper is to run these on choices generated by *neural
agents* (see train_agents.py), not just by the optimal policy, and ask
whether the recovered parameters mean anything mechanistically.
"""

from dataclasses import dataclass

import numpy as np
from scipy.optimize import minimize

from mdp import Panel, RustMDP


@dataclass
class EstimationResult:
    theta1: float
    rc: float
    log_likelihood: float
    converged: bool
    std_errors: tuple[float, float] | None = None


def _negative_log_likelihood(params: np.ndarray, panel: Panel,
                             template: RustMDP) -> float:
    theta1, rc = params
    if theta1 <= 0 or rc <= 0:
        return 1e12
    mdp = RustMDP(n_states=template.n_states, theta1=theta1, rc=rc,
                  beta=template.beta, trans_probs=template.trans_probs)
    ccp = mdp.solve(tol=1e-9).ccp_replace
    p = np.clip(ccp[panel.states], 1e-12, 1 - 1e-12)
    ll = np.where(panel.choices == 1, np.log(p), np.log1p(-p))
    return -ll.sum()


def estimate_nfxp(panel: Panel, template: RustMDP,
                  x0: tuple[float, float] = (0.02, 5.0)) -> EstimationResult:
    """Nested fixed point MLE for (theta1, rc); beta and transitions held at truth.

    `template` supplies the maintained assumptions (n_states, beta,
    trans_probs) — in the paper's language, the econometrician's model.
    """
    res = minimize(_negative_log_likelihood, x0=np.asarray(x0),
                   args=(panel, template), method="Nelder-Mead",
                   options={"xatol": 1e-6, "fatol": 1e-6, "maxiter": 2000})
    return EstimationResult(theta1=res.x[0], rc=res.x[1],
                            log_likelihood=-res.fun, converged=res.success)


def estimate_hotz_miller(panel: Panel, template: RustMDP,
                         min_visits: int = 30) -> EstimationResult:
    """CCP estimator (Hotz & Miller 1993) using replacement as renewal action.

    With T1EV shocks and a renewal action, V(x) = v1 - ln P1(x) where v1 is
    constant across x (replacing resets the state). Substituting into the
    log-odds phi(x) = ln(P1(x)/P0(x)) makes the constant terms cancel:

        phi(x) = -RC + theta1*x
                 + beta * [ E(-ln P1 | replace) - E(-ln P1 | x, keep) ]

    which is LINEAR in (theta1, RC) given nonparametric CCPs and known
    transitions. Estimated by visit-weighted least squares over states with
    at least `min_visits` observations. No fixed point is ever solved.
    """
    ccp_hat, counts = panel.empirical_ccp(template.n_states)
    mask = counts >= min_visits
    # Unvisited states have NaN CCPs but enter the continuation-value
    # correction through the transition matrix: fill them by interpolating
    # over visited states (extrapolation holds the boundary value).
    xs = np.arange(template.n_states, dtype=float)
    visited = counts > 0
    ccp_filled = np.interp(xs, xs[visited], ccp_hat[visited])
    p1 = np.clip(ccp_filled, 1e-4, 1 - 1e-4)

    p_keep = template.transition_matrix()
    p_replace = p_keep[0]
    neg_log_p1 = -np.log(p1)
    correction = template.beta * (p_replace @ neg_log_p1
                                  - p_keep @ neg_log_p1)

    # phi(x) - correction(x) = theta1 * x - RC, fit by weighted least squares
    x = np.arange(template.n_states, dtype=float)
    y = np.log(p1 / (1 - p1)) - correction
    w = counts.astype(float)
    design = np.column_stack([x[mask], -np.ones(mask.sum())])
    wls = np.sqrt(w[mask])
    coef, *_ = np.linalg.lstsq(design * wls[:, None], y[mask] * wls,
                               rcond=None)
    theta1_hat, rc_hat = coef

    ll = float(np.sum(np.where(panel.choices == 1,
                               np.log(p1[panel.states]),
                               np.log1p(-p1[panel.states]))))
    return EstimationResult(theta1=float(theta1_hat), rc=float(rc_hat),
                            log_likelihood=ll, converged=True)


if __name__ == "__main__":
    truth = RustMDP()
    panel = truth.solve().simulate(n_buses=500, n_periods=200)
    print("estimating on optimal-policy data (truth: theta1=0.05, rc=10.0)...")
    result = estimate_nfxp(panel, truth)
    print(f"NFXP:        theta1_hat = {result.theta1:.5f}, "
          f"rc_hat = {result.rc:.4f}")
    hm = estimate_hotz_miller(panel, truth)
    print(f"Hotz-Miller: theta1_hat = {hm.theta1:.5f}, rc_hat = {hm.rc:.4f}")
