"""Structural estimation of the Rust MDP from observed choice panels.

Week-5 workhorse. Two estimators:

1. `estimate_nfxp` — full-solution maximum likelihood (Rust's nested fixed
   point): for each candidate (theta1, rc), solve the MDP by value iteration
   and evaluate the logit likelihood of the observed choices. Slow but
   consistent and simple; used to validate the whole pipeline.

2. `estimate_hotz_miller` — TODO (week 5): CCP-based estimator exploiting
   replacement as a renewal action (finite dependence). Steps: (i) estimate
   CCPs nonparametrically from the panel, (ii) use the Hotz-Miller inversion
   with the renewal property to express choice-value differences in terms of
   CCPs and flow utilities, (iii) estimate (theta1, rc) by pseudo-likelihood.

The point of the paper is to run these on choices generated by *neural
agents* (see train_agents.py), not just by the optimal policy, and ask
whether the recovered parameters mean anything mechanistically.
"""

from dataclasses import dataclass

import numpy as np
from scipy.optimize import minimize

from mdp import Panel, RustMDP


@dataclass
class EstimationResult:
    theta1: float
    rc: float
    log_likelihood: float
    converged: bool
    std_errors: tuple[float, float] | None = None


def _negative_log_likelihood(params: np.ndarray, panel: Panel,
                             template: RustMDP) -> float:
    theta1, rc = params
    if theta1 <= 0 or rc <= 0:
        return 1e12
    mdp = RustMDP(n_states=template.n_states, theta1=theta1, rc=rc,
                  beta=template.beta, trans_probs=template.trans_probs)
    ccp = mdp.solve(tol=1e-9).ccp_replace
    p = np.clip(ccp[panel.states], 1e-12, 1 - 1e-12)
    ll = np.where(panel.choices == 1, np.log(p), np.log1p(-p))
    return -ll.sum()


def estimate_nfxp(panel: Panel, template: RustMDP,
                  x0: tuple[float, float] = (0.02, 5.0)) -> EstimationResult:
    """Nested fixed point MLE for (theta1, rc); beta and transitions held at truth.

    `template` supplies the maintained assumptions (n_states, beta,
    trans_probs) — in the paper's language, the econometrician's model.
    """
    res = minimize(_negative_log_likelihood, x0=np.asarray(x0),
                   args=(panel, template), method="Nelder-Mead",
                   options={"xatol": 1e-6, "fatol": 1e-6, "maxiter": 2000})
    return EstimationResult(theta1=res.x[0], rc=res.x[1],
                            log_likelihood=-res.fun, converged=res.success)


def estimate_hotz_miller(panel: Panel, template: RustMDP) -> EstimationResult:
    """CCP estimator (Hotz & Miller 1993) using replacement as renewal action."""
    raise NotImplementedError("week 5: implement CCP inversion estimator")


if __name__ == "__main__":
    truth = RustMDP()
    panel = truth.solve().simulate(n_buses=500, n_periods=200)
    print("estimating on optimal-policy data (truth: theta1=0.05, rc=10.0)...")
    result = estimate_nfxp(panel, truth)
    print(f"theta1_hat = {result.theta1:.5f}, rc_hat = {result.rc:.4f}, "
          f"converged = {result.converged}")
